# -*- coding: utf-8 -*-
"""kanak

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19bxsF7IquwS1snhi97xOO0zDGig9UkJx
"""

!pip install -q pyspark findspark

from pyspark.sql import SparkSession

spark = SparkSession.builder.appName("PySpark").getOrCreate()

print(spark.version)

from google.colab import files
uploaded = files.upload()

filename = list(uploaded.keys())[0]

df = spark.read.csv(
    filename,
    header=True,
    inferSchema=True
)

df.show(5)

df.printSchema()

df.select("name", "salary").show()

from pyspark.sql.functions import col

df.filter(col("salary") > 55000).show()

df = df.withColumnRenamed("salary", "Salary")

df.show()

from pyspark.sql.functions import lit

df = df.withColumn("Company", lit("Celebal"))

df.show()

df = df.na.fill({"Salary": 0})

df.show()

print("Total Records:", df.count())

df.select("name", "region", "Salary", "Company").show()

from pyspark.sql.functions import col

df.filter(col("Salary") >= 60000).show()

df.write.mode("overwrite").option("header", True).csv("Output_CSV")

df.write.mode("overwrite").parquet("Output_Parquet")

parquet_df = spark.read.parquet("Output_Parquet")
parquet_df.show()

print(df.count())

df.describe().show()

df.filter(df.Salary > 50000).explain(True)

df.groupBy("region").count().show()

parquet_df.filter(parquet_df.Salary > 50000).show()